[package]
name = "m32-wie-adapter"
version.workspace = true
edition.workspace = true
publish = false

[lib]
path = "src/lib.rs"

[dependencies]
async-trait.workspace = true
m32-emulator-api = { path = "../m32-emulator-api" }
tracing.workspace = true
wie_backend.workspace = true
wie_j2me.workspace = true
wie_util.workspace = true

[dev-dependencies]
m32-storage = { path = "../m32-storage" }
